name: mongodb
services:
    mongodb:
        container_name: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=VRuAd2Nvmp4ELHh5
            - MONGO_INITDB_DATABASE=elibrary
        volumes:
            - ./data:/data/db
        image: mongo:latest
        restart: always